### ISSUE TITLE
支持背景颜色为透明

### ISSUE THREAD

**Issue by imClumsyPanda** [LinXueyuanStdio/streamlit-markdown#2]
非常感谢开发出如此方便的component！请问可否考虑在后续版本中增加类似于streamlit自带的markdown显示功能的显示形式，如不加边框，且底色为透明色的形式呢？

**Comment by LinXueyuanStdio** [comment]
新版支持啦，设置 theme_color=“null” 即可

**Comment by imClumsyPanda** [comment]
太感谢啦！
